version: "3.9"

services:
  reverse-proxy:
    build: ./reverse-proxy
    container_name: gateway
    ports:
      - "8080:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/_nginx_healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    container_name: api
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  default:
    name: api_net
