version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"

  reverse-proxy:
    build: ./reverse-proxy
    container_name: gateway
    ports:
      - "8080:80"
    depends_on:
      - api
      - keycloak
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/_nginx_healthz"]
      interval: 10s
      timeout: 3s
      retries: 5

  api:
    build: ./api
    container_name: api
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  default:
    name: api_net
